### ISSUE TITLE
채팅룸 화면 구현 todo 리스트

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#288]
- [x] 초대 취소시 초대버튼 비활성화
https://github.com/ytw9699/Dokky/commit/444e2c98eac1123f3dd5aadd12173c5e154bf127

- [x] 채팅룸 입장시 메시지가 와있을때, 읽음 처리가 되지 않는 현상 고치기

**Comment by ytw9699** [comment]
### 공통페이지 common.jsp todo 리스트
 - [ ] 내가 읽지 않은 채팅메시지 카운트 가져와서 표시

**Comment by ytw9699** [comment]
채팅룸 입장시 메시지가 와있을때, 읽음 처리가 되지 않는 현상 고치기

- focusfunction의 코드의 위치 차이로 인해 문제해결..

https://github.com/ytw9699/Dokky/commit/a18db71844799a4bb8191d8db4cd53fd0f78ab84

**Comment by ytw9699** [comment]
- [x] 채팅메시지 보낸후 상대방에게 채팅카운트 실시간 알림 메시지 업데이트 요청하기
1:1의 채팅의 경우

- [ ] 채팅메시지 보낸후 상대방에게 채팅카운트 실시간 알림 메시지 업데이트 요청하기
멀티 채팅의 경우

**Comment by ytw9699** [comment]
- [ ]  채팅 보낸후 상대방에게 채팅카운트 실시간 알림 메시지 업데이트 요청하기 방식의 변경

**Comment by ytw9699** [comment]
채팅메시지 보낸후 상대방에게 채팅카운트 실시간 알림 메시지 업데이트 요청하기
1:1의 채팅의 경우 >> 문제가 또 발생

채팅창만 열어두고 다른창을 모두닫으면 웹소켓 객체가 사라져 보낼수가 없음.

부모창에서 자식창으로 웹소켓객체를 가져오던가 해야함

**Comment by ytw9699** [comment]
https://github.com/ytw9699/Dokky/issues/288#issuecomment-739524785
채팅창만 남겨두고 나머지창을 닫을때를 대비하여 코드를 다시 수정 + 변수이름 변경(가독성)
https://github.com/ytw9699/Dokky/commit/6bdf1e8b869e9715932658be84d883e56c01d2ce

**Comment by ytw9699** [comment]
- css 변경 > 채팅 내용이 많을때 정렬이 필요하다

- 디버그 잡기 > chatroom.innerHTML += html 태그 > 중간에 태그가 닫히지않은 상태로  ";" 을 찍어버리면 알아서 브라우저에서 태그를 자동완성시키고 닫아버리기 때문에, += 을 무조건 써선 안된다..

- 채팅보내기시 글자수 제한

https://github.com/ytw9699/Dokky/commit/a31ef6b6589adc3bea3d05461b7bbadc94114cbf

**Comment by ytw9699** [comment]
css 적용 및 프론트 조정
- 나와 상대방의 글자 백그라운드 표현과 세밀 간격 조정
https://github.com/ytw9699/Dokky/commit/932fedd995e45bf56a16ba5841bd8b95ce6bf8fa

**Comment by ytw9699** [comment]
- [x] 멀티채팅방에 입장시 채팅방 제목이 있다면, 아이디들을 가지고 오고, 제목이없다면 아이디와 닉네임들을 모두 가지고 와야함
아이디는 프로필사진을 불러오는데 쓰이고, 제목이 없다면 닉네임이 제목을 만드는데 쓰임
https://github.com/ytw9699/Dokky/commit/37ba6946e068371073ca8593cbd4584ede46a309

- [x] 멀티채팅방에서 메시지를 보낼시, 읽음 처리카운트가 -1 추가 되는 현상 고치기
